version : '3'

services:
  db:
    container_name: empleadoss_departamentoss
    image: mysql:8.2
    volumes:
      - ./mysql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'empleadoss_departamentoss'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'jorge.hurtado'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'